# Generated by Django 4.2.9 on 2024-02-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=25)),
                ('race', models.CharField(max_length=25)),
                ('server', models.CharField(max_length=30)),
            ],
        ),
    ]
