# Generated by Django 4.2.9 on 2024-02-15 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_jobs_characterunlockedjobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
