# Generated by Django 4.2.9 on 2024-02-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_rename_jobs_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expansion_pack',
            field=models.CharField(choices=[('ffxi', 'Final Fantasy XI'), ('RotZ', 'Rise of the Zilart'), ('ToAU', 'Treasures of Aht Urhgan'), ('WotG', 'Wings of the Goddess'), ('SoA', 'Seekers of Adoulin')], default='ffxi', max_length=4),
        ),
    ]
