# Generated by Django 4.2.9 on 2024-02-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_alter_job_expansion_pack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterunlockedjobs',
            old_name='character_id',
            new_name='character',
        ),
        migrations.RenameField(
            model_name='characterunlockedjobs',
            old_name='job_id',
            new_name='job',
        ),
    ]
