# Generated by Django 4.2.9 on 2024-02-15 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_rename_character_id_characterunlockedjobs_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterunlockedjobs',
            name='current_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)]),
        ),
    ]
