# Generated by Django 4.2.9 on 2024-02-25 06:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_characterunlockedjobs_current_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=25)),
                ('current_skill_level', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(417), django.core.validators.MinValueValidator(0)])),
                ('is_white_magic', models.BooleanField(default=False)),
                ('is_black_magic', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
            ],
        ),
    ]
