# Generated by Django 4.2.9 on 2024-02-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_magicskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magicskill',
            name='character',
        ),
    ]
