# Generated by Django 4.2.9 on 2024-02-25 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_remove_magicskill_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magicskill',
            name='current_skill_level',
        ),
    ]
