# Generated by Django 4.2.9 on 2024-02-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_remove_magicskill_current_skill_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MagicSkill',
        ),
    ]
