# Generated by Django 4.2.9 on 2024-02-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_delete_magicskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_name', models.CharField(max_length=50)),
            ],
        ),
    ]
