# Generated by Django 5.0.7 on 2024-07-26 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0011_spell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('hume_male', 'Hume ♂'), ('hume_female', 'Hume ♀'), ('elvaan_male', 'Elvaan ♂'), ('elvaan_female', 'Elvaan ♀'), ('tarutaru_male', 'Tarutaru ♂'), ('tarutaru_female', 'Tarutaru ♀'), ('galka', 'Galka'), ('mithra', 'Mithra')], default='hume_male', max_length=25),
        ),
        migrations.AlterField(
            model_name='character',
            name='server',
            field=models.CharField(choices=[('bahamut', 'Bahamut'), ('shiva', 'Shiva'), ('phoenix', 'Phoenix'), ('carbuncle', 'Carbuncle'), ('fenrir', 'Fenrir'), ('sylph', 'Sylph'), ('valefor', 'Valefor'), ('leviathan', 'Leviathan'), ('odin', 'Odin'), ('quetzalcoatl', 'Quetzalcoatl'), ('siren', 'Siren'), ('ragnarok', 'Ragnarok'), ('cerberus', 'Cerberus'), ('bismarck', 'Bismarck'), ('lakshmi', 'Lakshmi'), ('asura', 'Asura')], default='asura', max_length=30),
        ),
        migrations.CreateModel(
            name='JobArmor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('head', 'Head'), ('body', 'Body'), ('hands', 'Hands'), ('legs', 'Legs'), ('feet', 'Feet')], max_length=15)),
                ('acquired', models.BooleanField(default=False)),
                ('armor_type', models.CharField(choices=[('artifact', 'Artifact'), ('relic', 'Relic'), ('empyrean', 'Empyrean')], max_length=15)),
                ('reforged', models.BooleanField(default=False)),
                ('armor_version', models.CharField(choices=[('+1', '+1'), ('+2', '+2'), ('109', '109'), ('119', '119'), ('119 +1', '119 +1'), ('119 +2', '119 +2'), ('119 +3', '119 +3')], max_length=15)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.job')),
            ],
        ),
    ]
