# Generated by Django 5.0.7 on 2024-07-27 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0012_alter_character_character_name_alter_character_race_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobarmor',
            name='acquired',
        ),
        migrations.RemoveField(
            model_name='jobarmor',
            name='armor_version',
        ),
        migrations.RemoveField(
            model_name='jobarmor',
            name='reforged',
        ),
        migrations.CreateModel(
            name='CharacterJobArmor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired', models.BooleanField(default=False)),
                ('reforged', models.BooleanField(default=False)),
                ('upgrade_version', models.CharField(choices=[('+1', '+1'), ('+2', '+2'), ('109', '109'), ('119', '119'), ('119 +1', '119 +1'), ('119 +2', '119 +2'), ('119 +3', '119 +3')], max_length=15)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character')),
            ],
        ),
    ]
