# Generated by Django 5.0.7 on 2024-07-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0013_remove_jobarmor_acquired_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacterUnlockedJobs',
            new_name='CharacterJobs',
        ),
    ]
