# Generated by Django 5.0.7 on 2024-07-27 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0014_rename_characterunlockedjobs_characterjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterjobarmor',
            name='armor_piece',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='character.jobarmor'),
            preserve_default=False,
        ),
    ]
